[2024-02-28T18:55:50.963+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.Test_conexion manual__2024-02-28T18:55:49.989551+00:00 [queued]>
[2024-02-28T18:55:50.967+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.Test_conexion manual__2024-02-28T18:55:49.989551+00:00 [queued]>
[2024-02-28T18:55:50.967+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-28T18:55:50.973+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): Test_conexion> on 2024-02-28 18:55:49.989551+00:00
[2024-02-28T18:55:50.977+0000] {standard_task_runner.py:60} INFO - Started process 633 to run task
[2024-02-28T18:55:50.979+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'Test_conexion', 'manual__2024-02-28T18:55:49.989551+00:00', '--job-id', '462', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmphfd7lxs1']
[2024-02-28T18:55:50.981+0000] {standard_task_runner.py:88} INFO - Job 462: Subtask Test_conexion
[2024-02-28T18:55:51.022+0000] {task_command.py:423} INFO - Running <TaskInstance: first_dag.Test_conexion manual__2024-02-28T18:55:49.989551+00:00 [running]> on host 3d1772f4008a
[2024-02-28T18:55:51.070+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='Test_conexion' AIRFLOW_CTX_EXECUTION_DATE='2024-02-28T18:55:49.989551+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-28T18:55:49.989551+00:00'
[2024-02-28T18:55:51.071+0000] {sql.py:276} INFO - Executing: SELECT 1
[2024-02-28T18:55:51.075+0000] {base.py:83} INFO - Using connection ID 'postgres1' for task execution.
[2024-02-28T18:55:51.080+0000] {base.py:83} INFO - Using connection ID 'postgres1' for task execution.
[2024-02-28T18:55:51.082+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 391, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 158, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2024-02-28T18:55:51.086+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=first_dag, task_id=Test_conexion, execution_date=20240228T185549, start_date=20240228T185550, end_date=20240228T185551
[2024-02-28T18:55:51.092+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 462 for task Test_conexion (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 633)
[2024-02-28T18:55:51.119+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-28T18:55:51.131+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
